<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lumen</groupId>
        <artifactId>lumen-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath/>
    </parent>
    <artifactId>lumen-common-log</artifactId>
    <name>lumen-common-log</name>
    <description>日志通用模块</description>

    <dependencies>
        <dependency>
            <groupId>com.lumen</groupId>
            <artifactId>lumen-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>7.4</version>
        </dependency>
    </dependencies>
</project>