DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
    user_id            BIGINT          NOT NULL AUTO_INCREMENT,
    tenant_id          BIGINT          NOT NULL DEFAULT 1,
    dept_id            BIGINT          DEFAULT NULL,
    user_name          VARCHAR(50)     NOT NULL,
    nick_name          VARCHAR(50)     DEFAULT NULL,
    email              VARCHAR(100)    DEFAULT NULL,
    phonenumber        VARCHAR(20)     DEFAULT NULL,
    sex                CHAR(1)         DEFAULT '0',
    avatar             VARCHAR(500)    DEFAULT NULL,
    password           VARCHAR(100)    NOT NULL DEFAULT '',
    status             CHAR(1)         NOT NULL DEFAULT '0',
    data_scope         TINYINT         NOT NULL DEFAULT 1,
    mfa_secret         VARCHAR(100)    DEFAULT NULL,
    mfa_enabled        TINYINT         NOT NULL DEFAULT 0,
    pwd_expire_at      DATETIME        DEFAULT NULL,
    pwd_history        VARCHAR(2000)   DEFAULT '',
    id_card_enc        VARCHAR(500)    DEFAULT NULL,
    mobile_enc         VARCHAR(500)    DEFAULT NULL,
    email_enc          VARCHAR(500)    DEFAULT NULL,
    bank_card_enc      VARCHAR(500)    DEFAULT NULL,
    last_pwd_change    DATETIME        DEFAULT NULL,
    fail_count         INT             NOT NULL DEFAULT 0,
    lock_until         DATETIME        DEFAULT NULL,
    login_ip           VARCHAR(64)     DEFAULT NULL,
    login_date         DATETIME        DEFAULT NULL,
    remark             VARCHAR(500)    DEFAULT NULL,
    create_by          BIGINT          NOT NULL DEFAULT 0,
    create_time        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by          BIGINT          NOT NULL DEFAULT 0,
    update_time        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted            TINYINT         NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id),
    UNIQUE KEY uk_sys_user_tenant_username (tenant_id, user_name, deleted),
    KEY idx_sys_user_dept (dept_id),
    KEY idx_sys_user_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
